# Generated by Django 5.1.3 on 2024-12-02 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Welcome',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phrase', models.CharField(max_length=100)),
                ('sub_phrase', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('middle_phrase', models.CharField(max_length=50)),
                ('desc_phrase', models.CharField(max_length=200)),
            ],
        ),
    ]
