# Generated by Django 5.1.3 on 2024-12-03 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('n9admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='welcome',
            name='img',
            field=models.CharField(default='slide.png', max_length=400),
        ),
    ]
